### PR TITLE
11.0.5 QuestID Rename

### PR DESCRIPTION
**Pull request by Hyphie24**
So far only fix needed is QuestID rename from questId to questID in the WQAchievements.lua, there may be more changes needed but initial push for issue https://github.com/Urtgard/WQAchievements/issues/168

### CODE REVIEW

**Comment by Hyphie24** [comment]
Scanned all files with QuestId and changed to QuestID rename, as of right now no errors popping and /wqa working as intended

**Comment by Addonman** [comment]
I did fix .Now i am getting this error
Message: Interface/AddOns/WQAchievements/WQAchievements.lua line 1132:
   attempt to call method 'GetExpansionByquestID' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: GetExpansionByquestID()
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:1132: CheckReward()
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:1095: CheckItems()
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:984: Reward()
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:218:
      Interface/AddOns/WQAchievements/WQAchievements.lua:179
Locals:

**Comment by Addonman** [comment]
> I did fix .Now i am getting this error Message: Interface/AddOns/WQAchievements/WQAchievements.lua line 1132: attempt to call method 'GetExpansionByquestID' (a nil value) Debug: [string "=(tail call)"]: ? [string "=(tail call)"]: ? [string "=[C]"]: GetExpansionByquestID() [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:1132: CheckReward() [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:1095: CheckItems() [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:984: Reward() [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:218: Interface/AddOns/WQAchievements/WQAchievements.lua:179 Locals:

I did  change wrong and put some q instead of Q. And this was result .when i fixed quest into Quest errors were gone.

**Comment by tflo** [comment]
I applied the 4 commits to my copy (incl. the one from Oct 24) and can confirm that everything works fine.

**Comment by Urtgard** [comment]
Thanks again for your help.

**Pull request merged**
